# Generated by Django 3.2.15 on 2022-08-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('schedule', 'Schedule'), ('complete', 'Complete'), ('reschedule', 'Reschedule')], default='schedule', max_length=200),
        ),
    ]
